export { default as Hero } from './Hero';
export { default as About } from './About';
export { default as Account } from './Account';
export { default as Articles } from './Articles';
export { default as Landings } from './Landings';
export { default as Main } from './Main';
export { default as Pages } from './Pages';
export { default as Projects } from './Projects';
export { default as Signup } from './Signup';
